name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.0.0-nullsafety.3
homepage: https://github.com/fysoul17/google_maps_place_picker
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.1.0
  geolocator: ^7.7.1
  permission_handler: ^8.2.6
  provider: ^6.0.1
  google_maps_webservice: ^0.0.20-nullsafety.2
  google_api_headers: ^1.1.1
  tuple: ^2.0.0
  http: ^0.13.4
  td_flutter_core:
    git: https://github.com/tradedepot/td-flutter-core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
